Update os.yml

diff --git a/.github/workflows/os.yml b/.github/workflows/os.yml
--- a/.github/workflows/os.yml
+++ b/.github/workflows/os.yml
@@ -28,10 +28,9 @@ jobs:
         sudo chroot ./PeDitXOs-rootfs apt-get update
         sudo chroot ./PeDitXOs-rootfs apt-get install -y nano parted gzip curl wget fdisk whiptail dialog systemd grub-efi efibootmgr linux-image-amd64 linux-headers-amd64 live-boot
 
-    - name: Install lz4 tool
+    - name: Install xz-utils for compression
       run: |
-        sudo chroot ./PeDitXOs-rootfs apt-get update
-        sudo chroot ./PeDitXOs-rootfs apt-get install -y lz4
+        sudo chroot ./PeDitXOs-rootfs apt-get install -y xz-utils
 
     - name: Download installer script
       run: |
@@ -73,9 +72,14 @@ jobs:
         sudo chroot ./PeDitXOs-rootfs grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=PeDitXOs --removable
         sudo chroot ./PeDitXOs-rootfs update-grub
 
-    - name: Create initrd.img
+    - name: Create initrd.img with xz compression
       run: |
-        sudo chroot ./PeDitXOs-rootfs mkinitramfs -c lz4 -o /boot/initrd.img $(ls ./PeDitXOs-rootfs/boot/vmlinuz* | grep -oP 'vmlinuz-\d+\.\d+\.\d+.*' | head -n 1)
+        KERNEL_VERSION=$(ls ./PeDitXOs-rootfs/boot/vmlinuz* | grep -oP 'vmlinuz-\d+\.\d+\.\d+.*' | head -n 1)
+        if [ -z "$KERNEL_VERSION" ]; then
+          echo "Error: Kernel version not found!"
+          exit 1
+        fi
+        sudo chroot ./PeDitXOs-rootfs mkinitramfs -c xz -o /boot/initrd.img $KERNEL_VERSION
 
     - name: Create SquashFS filesystem
       run: |
